module.exports = [
  {
    id: 1,
    title: "Merry Go Round LS",
    composer: "Joe Hisaishi",
    url_path:
      "http://localhost:8080/public/Merry%20Go%20Round%20LEAD%20SHEET.pdf",
    tags: "['Studio Ghibli', 'jazz', 'lead sheets']",
    favorite: false,
  },
  {
    id: 2,
    title: "Misty",
    composer: "Erroll Garner",
    url_path: "http://localhost:8080/public/Misty.pdf",
    tags: "['jazz', 'lead sheets']",
    favorite: false,
  },
  {
    id: 3,
    title: "Sir Duke",
    composer: "Stevie Wonder",
    url_path: "http://localhost:8080/public/Sir-Duke.pdf",
    tags: "['classic soul']",
    favorite: true,
  },
  {
    id: 4,
    title: "Come Thou Fount",
    composer: "Nettleton",
    url_path: "http://localhost:8080/public/RLS_Come_Thou_Fount.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 5,
    title: "Great is Thy Faithfulness",
    composer: "William Runyan",
    url_path: "http://localhost:8080/public/RLS_Great_Is_Thy_Faithfulness.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 6,
    title: "Praise Ye The Lord The Almighty",
    composer: "Stralsund Gesangbuch",
    url_path:
      "http://localhost:8080/public/RLS_Praise_Ye_The_Lord_The_Almighty.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 7,
    title: "Ode to Joy",
    composer: "Ludwig van Beethoven",
    url_path: "http://localhost:8080/public/RLS_Joyful_Joyful.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 8,
    title: "How Great Thou Art",
    composer: "Wedish Folk Melody",
    url_path: "http://localhost:8080/public/RLS_How_Great_Thou_Art.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 9,
    title: "Rejoice The Lord Is King",
    composer: "",
    url_path: "http://localhost:8080/public/RLS_Rejoice_The_Lord_Is_King.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 10,
    title: "Simplemente Gracias",
    composer: "Calibre 50",
    url_path: "http://localhost:8080/public/Simplemente_gracias.pdf",
    tags: "['tuba']",
    favorite: false,
  },
  {
    id: 11,
    title: "Superstition",
    composer: "Stevie Wonder",
    url_path: "http://localhost:8080/public/Superstition.pdf",
    tags: "['classic soul']",
    favorite: true,
  },
  {
    id: 12,
    title: "1812 Overture",
    composer: "Pyotr Tchaikovsky",
    url_path: "http://localhost:8080/public/Tchaikovsky_1812Overture.pdf",
    tags: "['symphony']",
    favorite: true,
  },
  {
    id: 13,
    title: "Fountains of Rome",
    composer: "Ottorino Rhespighi",
    url_path: "http://localhost:8080/public/Respighi_Fountains.pdf",
    tags: "['symphony']",
    favorite: false,
  },
  {
    id: 14,
    title: "Enigma Variations",
    composer: "Edward Elgar",
    url_path: "http://localhost:8080/public/Elgar-Enigma-Variations.pdf",
    tags: "['symphony']",
    favorite: false,
  },
  {
    id: 15,
    title: "8th Symphony",
    composer: "Bruckner",
    url_path: "http://localhost:8080/public/Bruckner-Sym8.pdf",
    tags: "['symphony']",
    favorite: false,
  },
  {
    id: 16,
    title: "Damnation of Faust",
    composer: "Hector Berlioz",
    url_path: "http://localhost:8080/public/Berlioz_Damnation_of_Faust.pdf",
    tags: "['symphony']",
    favorite: false,
  },
  {
    id: 17,
    title: "Come Thou Fount (Guitar)",
    composer: "Nettleton",
    url_path: "http://localhost:8080/public/Come_Thou_Fount_Guitar.pdf",
    tags: "['hymns']",
    favorite: false,
  },
  {
    id: 18,
    title: "Farraday Fanfare",
    composer: "Zealtiel Zuniga",
    url_path: "http://localhost:8080/public/Farraday_Fanfare.pdf",
    tags: "['symphony', 'self-composed']",
    favorite: true,
  },
];
