module.exports = [
  {
    id: 1,
    title: "Merry Go Round LS",
    composer: "Joe Hisaishi",
    url_path: "http://localhost:8080/public/Merry-Go-Round-LS.pdf",
    tags: "['Studio Ghibli', 'jazz', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 2,
    title: "Misty",
    composer: "Erroll Garner",
    url_path: "http://localhost:8080/public/Misty.pdf",
    tags: "['jazz', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 3,
    title: "Sir Duke",
    composer: "Stevie Wonder",
    url_path: "http://localhost:8080/public/Sir-Duke.pdf",
    tags: "['classic soul', 'piano']",
    favorite: true,
    user_id: 1,
  },
  {
    id: 4,
    title: "Come Thou Fount",
    composer: "Nettleton",
    url_path: "http://localhost:8080/public/RLS_Come_Thou_Fount.pdf",
    tags: "['hymns', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 5,
    title: "Great is Thy Faithfulness",
    composer: "William Runyan",
    url_path: "http://localhost:8080/public/RLS_Great_Is_Thy_Faithfulness.pdf",
    tags: "['hymns', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 6,
    title: "Praise Ye The Lord The Almighty",
    composer: "Stralsund Gesangbuch",
    url_path:
      "http://localhost:8080/public/RLS_Praise_Ye_The_Lord_The_Almighty.pdf",
    tags: "['hymns', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 7,
    title: "Ode to Joy",
    composer: "Ludwig van Beethoven",
    url_path: "http://localhost:8080/public/RLS_Joyful_Joyful.pdf",
    tags: "['hymns', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 8,
    title: "How Great Thou Art",
    composer: "Wedish Folk Melody",
    url_path: "http://localhost:8080/public/RLS_How_Great_Thou_Art.pdf",
    tags: "['hymns', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 9,
    title: "Rejoice The Lord Is King",
    composer: "Charles Wesley",
    url_path: "http://localhost:8080/public/RLS_Rejoice_The_Lord_Is_King.pdf",
    tags: "['hymns', 'lead sheets', 'piano']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 10,
    title: "Simplemente Gracias",
    composer: "Calibre 50",
    url_path: "http://localhost:8080/public/Simplemente_gracias.pdf",
    tags: "['tuba']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 11,
    title: "Superstition",
    composer: "Stevie Wonder",
    url_path: "http://localhost:8080/public/Superstition.pdf",
    tags: "['classic soul', 'piano']",
    favorite: true,
    user_id: 1,
  },
  {
    id: 12,
    title: "1812 Overture",
    composer: "Pyotr Tchaikovsky",
    url_path: "http://localhost:8080/public/Tchaikovsky_1812Overture.pdf",
    tags: "['symphony']",
    favorite: true,
    user_id: 1,
  },
  {
    id: 13,
    title: "Fountains of Rome",
    composer: "Ottorino Rhespighi",
    url_path: "http://localhost:8080/public/Respighi_Fountains.pdf",
    tags: "['symphony']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 14,
    title: "Enigma Variations",
    composer: "Edward Elgar",
    url_path: "http://localhost:8080/public/Elgar-Enigma-Variations.pdf",
    tags: "['symphony']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 15,
    title: "8th Symphony",
    composer: "Bruckner",
    url_path: "http://localhost:8080/public/Bruckner-Sym8.pdf",
    tags: "['symphony']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 16,
    title: "Damnation of Faust",
    composer: "Hector Berlioz",
    url_path: "http://localhost:8080/public/Berlioz_Damnation_of_Faust.pdf",
    tags: "['symphony']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 17,
    title: "Come Thou Fount (Guitar)",
    composer: "Nettleton",
    url_path: "http://localhost:8080/public/Come_Thou_Fount_Guitar.pdf",
    tags: "['hymns']",
    favorite: false,
    user_id: 1,
  },
  {
    id: 18,
    title: "Farraday Fanfare",
    composer: "Zealtiel Zuniga",
    url_path: "http://localhost:8080/public/Farraday_Fanfare.pdf",
    tags: "['symphony', 'self-composed']",
    favorite: true,
    user_id: 1,
  },
  {
    id: 19,
    title: "2 Part Inventions",
    composer: "Johann Sebastian Bach",
    url_path: "http://localhost:8080/public/2-part-inventions.pdf",
    tags: "['classical', 'piano']",
    favorite: false,
    user_id: 2,
  },
  {
    id: 20,
    title: "6 English Suites",
    composer: "Johann Sebastian Bach",
    url_path: "http://localhost:8080/public/6-English-Suites.pdf",
    tags: "['classical', 'piano']",
    favorite: false,
    user_id: 2,
  },
  {
    id: 21,
    title: "10 Preludes",
    composer: "Sergei Rachmaninoff",
    url_path: "http://localhost:8080/public/10-Preludes.pdf",
    tags: "['romantic', 'piano']",
    favorite: false,
    user_id: 2,
  },
  {
    id: 22,
    title: "Invention in A minor",
    composer: "Johann Sebastian Bach",
    url_path: "http://localhost:8080/public/Invention-in-a-minor.pdf",
    tags: "['classical', 'piano']",
    favorite: false,
    user_id: 2,
  },
  {
    id: 23,
    title: "Moments Musicaux",
    composer: "Sergei Rachmaninoff",
    url_path: "http://localhost:8080/public/Moments-Musicaux.pdf",
    tags: "['romantic', 'piano']",
    favorite: false,
    user_id: 2,
  },
  {
    id: 24,
    title: "Suite For Tuba",
    composer: "Don Haddad",
    url_path: "http://localhost:8080/public/Suite-For-Tuba.pdf",
    tags: "['symphonic', 'tuba']",
    favorite: false,
    user_id: 2,
  },
  {
    id: 25,
    title: "Wayfaring Stranger",
    composer: "Mark Hayes",
    url_path: "http://localhost:8080/public/Wayfaring-Stranger.pdf",
    tags: "['jazz', 'piano']",
    favorite: false,
    user_id: 2,
  },
];
